name: CI # Continuous Integration

on:
  pull_request:

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

jobs:

  fmt:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update Rust toolchain
        run: rustup update stable --no-self-update
      - name: Check formatting
        run: cargo fmt --all --check

  clippy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update Rust toolchain
        run: rustup update stable --no-self-update
      - name: Clippy
        run: cargo clippy
