name: CI # Continuous Integration

on:
  pull_request:

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

jobs:

  fmt:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update Rust toolchain
        run: rustup update stable --no-self-update
      - name: Check formatting
        run: cargo fmt --all --check

  clippy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update Rust toolchain
        run: rustup update stable --no-self-update
      - name: Clippy
        run: |
          cargo clippy --all-targets --all-features \
          --workspace -- -D warnings

  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update Rust toolchain
        run: rustup update stable --no-self-update
      - name: Test
        run: cargo test

  doc:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update Rust toolchain
        run: rustup update stable --no-self-update
      - name: Check docs
        env:
          RUSTDOCFLAGS: -D warnings
        run: |
          cargo doc --no-deps --document-private-items \
            --all-targets \
            --all-features --workspace --examples
